title: Lusk.co
subtitle: "A fast, simple & powerful blog framework powered by Node.js."
description: "Lusk.co is a personal webserver "
author: Cody Lusk
language: en
timezone: America/Toronto

url: https://lusk.co
root: /
permalink: news/:year/:month/:day/:title/
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: false
per_page: 0

theme: legend
#deploy:
#  type: git
#  repo: git@github.com:iHongRen/legend.git

highlight:
  enable: true
  line_number: false

google_analytics: UA-72494889-6
github: ChaosZero112/lusk.co
